// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewProj.Classes
{
    [Table("Cart")]
    [Index(nameof(UserID), Name = "IX_Cart_UserID")]
    public partial class Cart
    {
        public Cart()
        {
            Orders = new HashSet<Order>();
        }

        [Key]
        public int ID { get; set; }
        public int TotalPrice { get; set; }
        public int Status { get; set; }
        public string UserID { get; set; }

        [ForeignKey(nameof(UserID))]
        [InverseProperty(nameof(AspNetUser.Carts))]
        public virtual AspNetUser User { get; set; }
        [InverseProperty(nameof(Order.Cart))]
        public virtual ICollection<Order> Orders { get; set; }
    }
}