// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewProj.Classes
{
    [Table("Product")]
    [Index(nameof(CategoryID), Name = "IX_Product_CategoryID")]
    [Index(nameof(OrderID), Name = "IX_Product_OrderID")]
    public partial class Product
    {
        [Key]
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }

        
        public string Category { get; set; }
        [StringLength(30)]
        public string? PhotoSrc { get; set; }

        
        public int? CategoryID { get; set; }
        public int? OrderID { get; set; }

        [ForeignKey(nameof(CategoryID))]
        [InverseProperty("Products")]
        [Display(Name = "Category")]
        public virtual Category CategoryNavigation { get; set; }
        [ForeignKey(nameof(OrderID))]
        [InverseProperty("Products")]
        public virtual Order Order { get; set; }

        [NotMapped]
        public IFormFile? Photo { get; set; }
    }
}